### ISSUE TITLE
validation tool

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/koffing#1]
Eu acho que precisamos uma função para checar a qualidade e checar os dados. Deve ter alguma guia na US-EPA. Vou procurar e achar. Também deve ter algo no pacote [openair](http://davidcarslaw.github.io/openair/).

**Comment by williamorim** [comment]
Como assim? Checar o que exatamente? :)

**Comment by ibarraespinosa** [comment]
Estava plotando o ano 2014, Ozonio, na estação IPEN. E tem ums valores acima de 1000 ug/m3 e me parecem errores de aparelho, calibração ou algo asim. Eu gostaría saber e a avaliação do padrão é feito com 100% das overvações ou algum percentil como é em outros paises.

Estou colocando os dados e a figuira é:

```
library(koffing)
library(ggplot2)
data("cetesb_param_ids")
data("cetesb_station_ids")
P22 <- scraper_cetesb(station = 95,
                      parameter = 63,
                      start = "01/01/2014",
                      end = "01/01/2015",
                      login = "sergio.ibarra@usp.br",
                      password = "nolodigas")
head(P22)
names(P22) <- gsub(pattern = " ", replacement = "", names(P22))
names(P22) <- gsub(pattern = "á", replacement = "a", names(P22))
names(P22) <- gsub(pattern = "é", replacement = "e", names(P22))
names(P22) <- gsub(pattern = "ç", replacement = "c", names(P22))
names(P22) <- gsub(pattern = "ó", replacement = "o", names(P22))
names(P22) <- gsub(pattern = "â", replacement = "a", names(P22))
P22$mes <- factor(x = months(P22$time),
                  levels = unique(months(P22$time)))

  ggplot(P22, aes(x = time, y = MediaHoraria, colour = MediaHoraria)) +
  geom_point() +
  facet_wrap(~mes, scales = "free_x")
```

![rplot1](https://user-images.githubusercontent.com/27447280/41755217-80f5c2ec-75ac-11e8-9cbe-bed5398ec1ed.png)
